### ISSUE TITLE
Project Cannot be opened in 4.23

### ISSUE THREAD

**Issue by Dragonlizard02** [robertsmieja/UE4-Maze#2]
Says that maze was built in a different version and then asks if you want it to be rebuilt and then states that it cannot be compiled. Try Rebuilding from source manually.

**Comment by robertsmieja** [comment]
I did not check in the binary output on purpose, so you do need to rebuild.

I can not reproduce your error: https://i.imgur.com/pkAfncM.jpg
I'm able to launch the editor from Visual Studio 2019, and launch the editor/game without Visual Studio.

If you have any other information on how I can reproduce, let me know.
